Updated Drive Code without Abstraction
Swartdogs/ChargedCode pull request #2
Opened 2023-01-14 17:21 UTC by CanineSatsuma6

This is the updated drivebase code that doesn't rely on the abstraction library from previous seasons

2023-01-14 21:19 UTC, edenreicherts requested changes

2023-01-14 21:19 UTC, edenreicherts commented on src/main/java/frc/robot/subsystems/drive/SwerveModule.java
> +public abstract class SwerveModule extends Vector
Don't make this abstract

2023-01-14 21:19 UTC, edenreicherts commented on src/main/java/frc/robot/subsystems/drive/SwerveModule.java
> +    protected PIDControl           _rotatePID;
Private not protected

2023-01-14 21:19 UTC, edenreicherts commented on src/main/java/frc/robot/subsystems/drive/SwerveModule.java
> +    }
Shouldn't exist anymore

2023-01-14 21:19 UTC, edenreicherts commented on src/main/java/frc/robot/subsystems/drive/SwerveModule.java
> +        return _positionSensor.get();
Get drive position should return the distance the drive wheel has changed

2023-01-14 21:19 UTC, edenreicherts commented on src/main/java/frc/robot/subsystems/drive/Drive.java
> +public abstract class Drive extends SubsystemBase
Should not be abstract

2023-01-14 21:19 UTC, edenreicherts commented on src/main/java/frc/robot/subsystems/drive/Drive.java
> +    private   double         _translationCloseMaxSpeed;
Protected should be private

2023-01-14 21:19 UTC, edenreicherts commented on src/main/java/frc/robot/subsystems/drive/Drive.java
> +        resetOdometer();
Move these to the end of the constructor, and remove function

2023-01-14 21:19 UTC, edenreicherts commented on src/main/java/frc/robot/subsystems/drive/Drive.java
> +    public SwerveModule getSwerveModule(int index)
Remove

2023-01-14 21:30 UTC, JoeKangas commented on src/main/java/frc/robot/subsystems/drive/Drive.java
> +    public SwerveModule getSwerveModule(int index)
Just public SwerveModule?

2023-01-15 03:07 UTC, chexbox commented on src/main/java/frc/robot/subsystems/drive/Drive.java
> +    public Drive()
The contents of HardwareDrive needs to be copied in here

2023-01-15 03:07 UTC, chexbox commented on src/main/java/frc/robot/subsystems/drive/Drive.java
> +    public SwerveModule getSwerveModule(int index)
> Just public SwerveModule?

What.

2023-01-15 03:07 UTC, chexbox commented on src/main/java/frc/robot/subsystems/drive/Drive.java
> +        double PIDPosition = Math.toRadians(_rotateSetpoint - getHeading());
need to change this

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/Drive.java
> +public class Drive
This class should be named `SwerveModule`

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/Drive.java
> +    private final AnalogInput        _absoluteEncoder;
Our code from last year used the `AnalogPotentiometer` class. We should use that again this year

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/Drive.java
> +        this._absoluteEncoderReversed  = absoluteEncoderReversed;
I don't know if we've talked about this before, but putting the `this` keyword before a variable indicates that the variable we're accessing is a member variable. Usually this is useful when we have a member variable that has the same name as a parameter, like this:

```java
public class MyClass
{
   private int myParameter;

   public MyClass(int myParameter)
   {
      this.myParameter = myParameter;
   }
}
```

In this example, `this.myParameter` is the private member variable, and `myParameter` is the parameter to the constructor.

In the code you wrote, the member variable and the parameter have different names: `_absoluteEncoderOffsetRad` vs. `absoluteEncoderOffsetRad`. Since they're different, you don't need the `this` part at the beginning.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/Drive.java
> +        _rotateEncoder                 = _rotateMotor.getEncoder();
Super minor style thing, but I like to keep all of the "assignment" type initialization lines above the "function call" type initialization lines.

For example, instead of

```java
_driveMotor.setInverted(driveMotorReversed);

_driveEncoder = _driveMotor.getEncoder();
```

I would prefer to do this:

```java
_driveEncoder = _driveMotor.getEncoder();

_driveMotor.setInverted(driveMotorReversed);
```

This includes line 51 as well, when you're creating the `_rotatePIDController` variable.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/Drive.java
> +        _driveMotor.set(state.speedMetersPerSecond / DriveConstants.kPhysicalMaxSpeedMetersPerSecond);
I need to think about how I want to do this, but I don't want to use a constant scaling factor to go from the desired velocity to the desired percent output. We can talk more about how to do this.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/Drive.java
> +        SmartDashboard.putString("Swerve[" + _absoluteEncoder.getChannel() + "] state", state.toString());
This line is just for debugging, we don't need to keep it.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/DriveSubsystem.java
> +    }
We don't need this function. It's just for debugging.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/DriveSubsystem.java
> +        }).start();
We should double check the documentation on the NavX. I'd like to create a constant variable for the sleep timer.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/DriveSubsystem.java
> +public class DriveSubsystem extends SubsystemBase
If we rename your `Drive` class to `SwerveModule`, we can rename this class to `Drive`.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +                                Supplier<Double> rotateSpdFunction, Supplier<Boolean> fieldOrientedFunction)
I want to make a few changes to the constructor:
1. Let's get rid of the `DriveSubsystem` parameter (in my next comment, I'll explain what we're going to do instead).
2. Rather than using `Supplier<Double>`, we can use the dedicated `DoubleSupplier` class.
3. Similarly, let's use `BooleanSupplier` instead of `Supplier<Boolean>`

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/subsystems/DriveSubsystem.java
> +{
One thing I'd like to try this year is making all of our subsystems [singletons](https://en.wikipedia.org/wiki/Singleton_pattern). The basic idea behind it is that there's only ever one instance of each of our subsystems, and, because there's only one instance, we can access the subsystem from anywhere without having to pass the subsystem through functions and constructors.

To implement this, we need a `static` private variable that represents our single instance, and we need a function to return that particular instance. The code will look like this:

```java
public class Drive
{
   private static Drive _instance;

   public static Drive getInstance()
   {
      if (_instance == null)
      {
         _instance = new Drive();
      }

      return _instance;
   }
}
```

Then, we'll need to make the constructor for the class `private` (currently on line 53). This way, no one can create a new instance of the subsystem, but we can get a reference to one by calling the `Drive.getInstance()` method. When we call it, we'll either create a new instance of the `Drive` subsystem, or use the existing one if it's already been created.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +    private final SlewRateLimiter xLimiter, yLimiter, turningLimiter;
We won't use the `SlewRateLimiter` objects in our command. This object is intended to help with smoothing joystick input, but we'll be managing joystick functionality through `RobotContainer`, not through this command.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +public class CmdDriveWithJoystick extends CommandBase
Just a thought, and I'd like to have some more discussion on this, but I don't know that I love the convention of putting `Cmd` at the beginning of our commands.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +        this.turningLimiter = new SlewRateLimiter(DriveConstants.kTeleDriveMaxAngularAccelerationUnitsPerSecond);
Like I mentioned in an earlier comment, we don't need the `this` keyword before our parameters. Also, line up the equals signs.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +    private final SlewRateLimiter xLimiter, yLimiter, turningLimiter;
Our member variables should start with `_`.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +    private final Supplier<Double> xSpdFunction, ySpdFunction, rotateSpdFunction;
While technically doable according to the language, I don't want to declare multiple variables on the same line like this. Let's create each variable on its own line.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +        this.driveSubsystem = driveSubsystem;
If we make our `Drive` subsystem a singleton, this line will change to:

```java
_driveSubsystem = Drive.getInstance();
```

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +    }
We're not using this function, so let's get rid of the clutter.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +        rotateSpeed = Math.abs(rotateSpeed) > OIConstants.kDeadband ? rotateSpeed : 0.0;
Deadbands will be calculated in `RobotContainer`, so we don't need to do it here.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +        }
If we initialize the `chassisSpeeds` variable to `new ChassisSpeeds(xSpeed, ySpeed, rotateSpeed)`, we can get rid of the `else` block:

```java
ChassisSpeeds chassisSpeeds = new ChassisSpeeds(xSpeed, ySpeed, rotateSpeed);

if (fieldOrientedFunction.get())
{
    // Relative to field
    chassisSpeeds = ChassisSpeeds.fromFieldRelativeSpeeds(xSpeed, ySpeed, rotateSpeed, driveSubsystem.getRotation2d());
}
```

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +        }
Curly braces go on the next line.

2023-01-16 07:02 UTC, CanineSatsuma6 commented on src/main/java/frc/robot/commands/CmdDriveWithJoystick.java
> +    }
I did look up the source of truth on this ([link](https://github.com/wpilibsuite/allwpilib/blob/5cb0340a8cdb02c77330fd8e6bb4585a29c6ca5a/wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java#L47)). Commands, by default, return `false` for `isFinished`, so we can remove this function if we want.

2023-01-22 00:39 UTC, closed without merging